#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DESIGN_DOC="$ROOT_DIR/docs/DESIGN.md"
ARCH_DIR="$ROOT_DIR/docs/architecture"
BASELINE_EDGES="$ARCH_DIR/last_edges.txt"
SUMMARY_DOC="$ROOT_DIR/docs/ARCHITECTURE_CHANGE_SUMMARY.md"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

mkdir -p "$ARCH_DIR"

if [[ ! -f "$DESIGN_DOC" ]]; then
  echo "Missing required file: $DESIGN_DOC" >&2
  exit 1
fi

if ! grep -q '<!-- BEGIN AUTO-GENERATED:ARCHITECTURE -->' "$DESIGN_DOC"; then
  echo "Missing architecture begin marker in $DESIGN_DOC" >&2
  exit 1
fi

if ! grep -q '<!-- END AUTO-GENERATED:ARCHITECTURE -->' "$DESIGN_DOC"; then
  echo "Missing architecture end marker in $DESIGN_DOC" >&2
  exit 1
fi

MODULE_PATH="$(awk '/^module / { print $2; exit }' "$ROOT_DIR/go.mod")"
if [[ -z "$MODULE_PATH" ]]; then
  echo "Unable to read module path from $ROOT_DIR/go.mod" >&2
  exit 1
fi

RAW_IMPORTS="$TMP_DIR/raw_imports.txt"
COMPONENT_EDGES="$TMP_DIR/component_edges.txt"
CURRENT_EDGES="$TMP_DIR/current_edges.txt"
NODES_FILE="$TMP_DIR/nodes.txt"
DIAGRAM_BLOCK="$TMP_DIR/diagram_block.md"

cd "$ROOT_DIR"

if command -v go >/dev/null 2>&1; then
  go list -f '{{.ImportPath}} {{join .Imports " "}}' ./... > "$RAW_IMPORTS"
else
  : > "$RAW_IMPORTS"

  while IFS= read -r go_file; do
    rel_dir="$(dirname "${go_file#./}")"
    if [[ "$rel_dir" == "." ]]; then
      src_pkg="$MODULE_PATH"
    else
      src_pkg="$MODULE_PATH/$rel_dir"
    fi

    imports="$(awk '
      /^import[[:space:]]+\(/ { in_block = 1; next }
      in_block && /^\)/ { in_block = 0; next }
      in_block {
        if (match($0, /"[^"]+"/)) {
          val = substr($0, RSTART + 1, RLENGTH - 2)
          printf "%s ", val
        }
        next
      }
      /^import[[:space:]]+"[^"]+"/ {
        if (match($0, /"[^"]+"/)) {
          val = substr($0, RSTART + 1, RLENGTH - 2)
          printf "%s ", val
        }
      }
    ' "$go_file")"

    printf '%s %s\n' "$src_pkg" "$imports" >> "$RAW_IMPORTS"
  done < <(find . \
    -type d \( -name vendor -o -name .git \) -prune -o \
    -type f -name '*.go' -print | sort)
fi

awk -v module="$MODULE_PATH" '
function normalize_pkg(pkg, rel, arr) {
  if (pkg == module) {
    return "root"
  }
  if (index(pkg, module "/") != 1) {
    return ""
  }

  rel = substr(pkg, length(module) + 2)
  split(rel, arr, "/")

  if (arr[1] == "cmd") {
    return "cmd"
  }
  if (arr[1] == "pkg" && arr[2] != "") {
    return "pkg/" arr[2]
  }
  if (arr[1] == "integration") {
    return "integration"
  }
  return arr[1]
}

{
  src = normalize_pkg($1)
  if (src == "") {
    next
  }

  for (i = 2; i <= NF; i++) {
    dst = normalize_pkg($i)
    if (dst == "" || src == dst) {
      continue
    }
    print src " -> " dst
  }
}
' "$RAW_IMPORTS" | sort -u > "$COMPONENT_EDGES"

cp "$COMPONENT_EDGES" "$CURRENT_EDGES"

awk -F ' -> ' '
{
  print $1
  print $2
}
' "$CURRENT_EDGES" | sort -u > "$NODES_FILE"

node_id() {
  echo "$1" | tr '/.-' '___' | tr -cd '[:alnum:]_'
}

label_for() {
  case "$1" in
    root) echo "main.go (root)" ;;
    cmd) echo "cmd/ (CLI commands)" ;;
    pkg/reporting) echo "pkg/reporting (report generation and capture)" ;;
    pkg/formatter) echo "pkg/formatter (TXT/CSV/table output)" ;;
    integration) echo "integration/ (integration test harness)" ;;
    *) echo "$1" ;;
  esac
}

{
  echo '```mermaid'
  echo 'flowchart LR'

  while IFS= read -r node; do
    [[ -z "$node" ]] && continue
    printf '  %s["%s"]\n' "$(node_id "$node")" "$(label_for "$node")"
  done < "$NODES_FILE"

  while IFS= read -r edge; do
    [[ -z "$edge" ]] && continue
    src="${edge%% -> *}"
    dst="${edge##* -> }"
    printf '  %s --> %s\n' "$(node_id "$src")" "$(node_id "$dst")"
  done < "$CURRENT_EDGES"

  echo '```'
} > "$DIAGRAM_BLOCK"

UPDATED_DESIGN="$TMP_DIR/DESIGN.updated.md"
awk -v blk="$DIAGRAM_BLOCK" '
BEGIN { inblock = 0 }
/<!-- BEGIN AUTO-GENERATED:ARCHITECTURE -->/ {
  print
  while ((getline line < blk) > 0) {
    print line
  }
  close(blk)
  inblock = 1
  next
}
/<!-- END AUTO-GENERATED:ARCHITECTURE -->/ {
  inblock = 0
  print
  next
}
!inblock { print }
' "$DESIGN_DOC" > "$UPDATED_DESIGN"

mv "$UPDATED_DESIGN" "$DESIGN_DOC"

ADDED_FILE="$TMP_DIR/added_edges.txt"
REMOVED_FILE="$TMP_DIR/removed_edges.txt"

if [[ -f "$BASELINE_EDGES" ]]; then
  comm -13 "$BASELINE_EDGES" "$CURRENT_EDGES" > "$ADDED_FILE" || true
  comm -23 "$BASELINE_EDGES" "$CURRENT_EDGES" > "$REMOVED_FILE" || true
else
  cp "$CURRENT_EDGES" "$ADDED_FILE"
  : > "$REMOVED_FILE"
fi

{
  echo '# Architecture Change Summary'
  echo
  echo 'This file is generated by scripts/update_architecture_diagram.sh.'
  echo 'It compares the current internal package dependency graph to docs/architecture/last_edges.txt.'
  echo
  if [[ -f "$BASELINE_EDGES" ]]; then
    echo "- Baseline edges: $(wc -l < "$BASELINE_EDGES" | tr -d ' ')"
  else
    echo '- Baseline edges: 0 (no prior baseline found)'
  fi
  echo "- Current edges: $(wc -l < "$CURRENT_EDGES" | tr -d ' ')"
  echo "- Added edges: $(wc -l < "$ADDED_FILE" | tr -d ' ')"
  echo "- Removed edges: $(wc -l < "$REMOVED_FILE" | tr -d ' ')"
  echo

  echo '## Added'
  if [[ -s "$ADDED_FILE" ]]; then
    while IFS= read -r line; do
      echo "- $line"
    done < "$ADDED_FILE"
  else
    echo '- None'
  fi
  echo

  echo '## Removed'
  if [[ -s "$REMOVED_FILE" ]]; then
    while IFS= read -r line; do
      echo "- $line"
    done < "$REMOVED_FILE"
  else
    echo '- None'
  fi
} > "$SUMMARY_DOC"

cp "$CURRENT_EDGES" "$BASELINE_EDGES"

echo "Updated architecture diagram in $DESIGN_DOC"
echo "Updated architecture change summary in $SUMMARY_DOC"
echo "Updated baseline edges in $BASELINE_EDGES"
